[book]
authors = ["Albert O'Shea"]
language = "en"
src = "src"
title = "Imp"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/imp-nix/imp-nix"
edit-url-template = "https://github.com/imp-nix/imp-nix/edit/main/docs/{path}"
no-section-label = true

[output.html.print]
enable = false
